name: Sync to Habitica

on:
  schedule:
  # run every day at 03:00
    - cron:  '0 3 * * *'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.10.9]
        poetry-version: [1.3.2]

    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install Poetry
        run: pipx install poetry

      - name: Setup Poetry cache
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'poetry'

      - name: Check Poetry installation
        run: poetry --version

      - name: Install dependencies
        run: poetry install --only main

      - name: run sync
        run: |
          poetry run python src/main.py
        env:
          PYTHONPATH: "src"  # <---- added env var
          TODOIST_USER_ID: ${{ secrets.TODOIST_USER_ID }}
          TODOIST_API_KEY: ${{ secrets.TODOIST_API_KEY }}
          HABITICA_USER_ID: ${{ secrets.HABITICA_USER_ID }}
          HABITICA_API_KEY: ${{ secrets.HABITICA_API_KEY }}
