name: Sync to Habitica

on:
    push:
      branches:
        ["autosync"]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.10.6]
        poetry-version: [1.1.12]

    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install Poetry
        run: pipx install poetry

      - name: Setup Poetry cache
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'poetry'

      - name: Check Poetry installation
        run: poetry --version

      - name: Install dependencies
        run: poetry install --no-root

      - name: run sync
        run: |
          poetry run python src/main.py
        env:
          PYTHONPATH: "src"  # <---- added env var
          TODOIST_USER_ID: ${{ secrets.TODOIST_USER_ID }}
          TODOIST_API_KEY: ${{ secrets.TODOIST_API_KEY }}
          HABITICA_USER_ID: ${{ secrets.HABITICA_USER_ID }}
          HABITICA_API_KEY: ${{ secrets.HABITICA_API_KEY }}
