name: Sync to Habitica

on:
  # manually triggered
  workflow_dispatch:
  schedule:
  # run every hour on the hour
    - cron:  '0 * * * *'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.10.6]
        poetry-version: [1.1.12]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install poetry ${{ matrix.poetry-version }}
      run: |
        python -m ensurepip
        python -m pip install --upgrade pip
        python -m pip install poetry==${{ matrix.poetry-version }}

    - name: View poetry --help
      run: poetry --help

    - name: Install dependencies
      shell: bash
      run: python -m poetry install --no-root

    - name: run sync
      run: |
        python -m poetry run python -m src/main.py
      env:
        TODOIST_USER_ID: ${{ secrets.TODOIST_USER_ID }}
        TODOIST_API_KEY: ${{ secrets.TODOIST_API_KEY }}
        HABITICA_USER_ID: ${{ secrets.HABITICA_USER_ID }}
        HABITICA_API_KEY: ${{ secrets.HABITICA_API_KEY }}